### ISSUE TITLE
Link to S. Adaszewski's OpenCL implementations?

### ISSUE THREAD

**Issue by poke1024** [innolitics/natural-neighbor-interpolation#6]
Not sure if you're aware of these, but Stanislaw Adaszewski made an experimental but interesting OpenCL implementation of your algorithm. Maybe they can be linked here?

See https://github.com/sadaszewski/nn3d/ and https://adared.ch/fast-discrete-approximation-of-natural-neighbor-interpolation-in-3d/

**Comment by johndgiese** [comment]
Thanks for pointing this out; I added a link!
